server:
  port: 8003
spring:
  application:
    name: qbike-trip    # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/${DB_SCHEMA}?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    tomcat:
      max-active: 3
      min-idle: 1
  redis:
    host: ${REDIS_HOST}
    timeout: 2000
    database: ${REDIS_DB}
    pool:
      max-active: 20
      min-idle: 1
      max-idle: 5
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true