server:
  port: 8000
spring:
  application:
    name: qbike-uc    # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qbike?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    tomcat:
      max-active: 5
      min-idle: 1
                      # 指定数据源类型
#    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
#    data: classpath:data.sql            # 指定h2数据库的insert脚本
  h2:
    console:
      enabled: true
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true